title: The-F00L's Blog
description: "The-F00L's Blog about computer related stuff programming ,hacking and in general "
author:
  name: "The-F00L"
  email: "thezero.thef00l@gmail.com"
  url: "https://the-f00l.github.io/blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 7
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "The-F00L"
year : "2020"
